stubModules: ['jst', 'text']
modules:
  - name: 'themes/press-play/main'
    insertRequire: ['themes/press-play/main']
  - name: 'themes/press-play/editor/main'
    insertRequire: ['themes/press-play/editor/main']
    helpers:
      - {
          label: 'editor',
          pattern: 'at-pp',
          replace: 'at-pp/editor'
        }
  - name: 'themes/steady-sun/main'
    insertRequire: ['themes/steady-sun/main']
  - name: 'themes/steady-sun/editor/main'
    insertRequire: ['themes/steady-sun/editor/main']
    helpers:
      - {
          label: 'editor',
          pattern: '(at-ss)|(themes/common)',
          replace: 'at-ss/editor'
        }
paths:
  'at-common': 'themes/common'
  'at-pp': 'themes/press-play'
  'at-ss': 'themes/steady-sun'
  'jquery': 'jquery'
  'underscore': 'underscore'
  'backbone': 'backbone'
  'quilt': 'quilt'
  'supermodel': 'supermodel'
  'list': 'list'
  'jquery_ui': 'jquery-ui'
  'soundmanager2': 'soundmanager2/soundmanager2'
  'easing': 'jquery.easing.1.3'
  'fancybox': 'fancybox/jquery.fancybox'
  'jquery.ui.widget': 'jquery.fileupload/jquery.ui.widget'
  'iframe_transport': 'jquery.fileupload/jquery.iframe-transport'
  'fileupload': 'jquery.fileupload/jquery.fileupload'
  'redactor': 'redactor'
  'moment': 'moment'
  'text': 'text'
  'jst': 'jst'
  'help': 'help'
shim:
  underscore:
    exports: '_'
  backbone:
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  jquery:
    exports: 'jQuery'
  jquery_ui:
    deps: ['jquery']
    exports: 'jQuery'
  supermodel:
    deps: ['backbone']
    exports: 'Supermodel'
  quilt:
    deps: ['backbone']
    exports: 'Quilt'
  list:
    deps: ['quilt']
    exports: 'List'
  easing:
    deps: ['jquery']
    exports: '$'
  fancybox:
    deps: ['jquery']
    exports: '$'
  fileupload:
    deps: ['jquery', 'iframe_transport']
  redactor:
    deps: ['jquery']
    exports: '$'
