modules:
  - name: 'themes/press-play/main'
  - name: 'themes/press-play/editor/main'
    helpers: ['editor']
    map:
      '*':
        'views/pages/listen': 'help!views/pages/listen'
        'views/pages/news': 'help!views/pages/news'
        'views/pages/tour': 'help!views/pages/tour'
        'views/pages/photos': 'help!views/pages/photos'
        'views/pages/contact': 'help!views/pages/contact'
        'views/pages/custom': 'help!views/pages/custom'
        'views/links/navigation': 'help!views/links/navigation'
        'views/links/nav-item': 'help!views/links/nav-item'
        'views/music/album': 'help!views/music/album'
        'views/music/track': 'help!views/music/track'
        'views/visual/photo': 'help!views/visual/photo'
        'views/visual/ticker': 'help!views/visual/ticker'
        'views/visual/background': 'help!views/visual/background'
        'views/content/concert': 'help!views/content/concert'
        'views/content/post': 'help!views/content/post'
stubModules: ['jst', 'text']
exclude: ['text']
paths:
  'at-pp': 'themes/press-play'
  jquery: 'jquery'
  underscore: 'underscore'
  backbone: 'backbone'
  quilt: 'quilt'
  supermodel: 'supermodel'
  list: 'list'
  jquery_ui: 'jquery-ui'
  jplayer: 'jplayer/jquery.jplayer.min'
  easing: 'jquery.easing.1.3'
  fancybox: 'fancybox/jquery.fancybox'
  'jquery.ui.widget': 'jquery.fileupload/jquery.ui.widget'
  iframe_transport: 'jquery.fileupload/jquery.iframe-transport'
  fileupload: 'jquery.fileupload/jquery.fileupload'
  redactor: 'redactor'
  moment: 'moment'
  text: 'text'
  jst: 'jst'
  help: 'help'
shim:
  backbone:
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  underscore:
    exports: '_'
  jquery:
    exports: 'jQuery'
  jquery_ui:
    deps: ['jquery']
    exports: 'jQuery'
  supermodel:
    deps: ['backbone']
    exports: 'Supermodel'
  quilt:
    deps: ['backbone']
    exports: 'Quilt'
  list:
    deps: ['quilt']
    exports: 'List'
  jplayer:
    deps: ['jquery']
    exports: '$'
  easing:
    deps: ['jquery']
    exports: '$'
  fancybox:
    deps: ['jquery']
    exports: '$'
  fileupload:
    deps: ['jquery', 'iframe_transport']
  redactor:
    deps: ['jquery']
    exports: '$'
